### ISSUE TITLE
FYI: Alternative OrgMode.jl project

### ISSUE THREAD

**Issue by tecosaur** [TimQuelch/OrgMode.jl#19]
Hello!

Before I went ahead creating an Org parsing library for Julia I did a quick search and your project turned up. I've gone ahead and made my own thing, but thought I'd let you know in case it's of interest 🙂.

https://github.com/tecosaur/OrgMode.jl

**Comment by TimQuelch** [comment]
This looks great! My project is pretty much abandoned; I realised that the project was far bigger than I expected and didn't have the time to dedicate to it. I'll likely use your library in the future!
